# This file contains the configuration for the genetic algorithm
model:
  class_path: ohc.genetic_algorithm.EvoCLAP:
  init_args:
    problem: 
      class_path: ohc.search.genetic_algorithm.FindMySound  # Path to the problem class
      init_args:  # Arguments for the problem class
        num_params: 10
        min_value: 0.0
        max_value: 1.0
        batch_size: 32
        fitness_function: 
          class_path: ohc.fitness.fitness.FitnessFunction  # Path to the fitness function class
          init_args: 
            vsti_host: 
              class_path: ohc.fitness.vsthost.VstiHost
              init_args:
                vst_file: Path to the VST file
                inactive_param_behaviour: fixed
            clap_similarity: 
              class_path: ohc.fitness.fitness.CLAPSimilarity
    searcher_class: 
      class_path: evotorch.algorithms.SNES  # Path to the searcher class
        population_size: 100  # Population size for the evolutionary algorithm
    max_generations: 100  # Maximum number of generations for the evolutionary algorithm
    initial_solution_path: null  # Path to the initial solution, if any
    device: "cuda"  # Device for the evolutionary algorithm

